export const LOST_PASSWORD_REQUESTED = 'LOST_PASSWORD_REQUESTED';
export const LOST_PASSWORD_STARTED = 'LOST_PASSWORD_STARTED';
export const LOST_PASSWORD_SUCCESS = 'LOST_PASSWORD_SUCCESS';
export const LOST_PASSWORD_ERROR = 'LOST_PASSWORD_ERROR';

export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED';
export const RESET_PASSWORD_STARTED = 'RESET_PASSWORD_STARTED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
