export const CREATE_EVENT_REQUESTED = 'CREATE_EVENT_REQUESTED';
export const CREATE_EVENT_STARTED = 'CREATE_EVENT_STARTED';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const UPDATE_EVENT_REQUESTED = 'UPDATE_EVENT_REQUESTED';
export const UPDATE_EVENT_STARTED = 'UPDATE_EVENT_STARTED';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_ERROR = 'UPDATE_EVENT_ERROR';

export const DELETE_EVENT_REQUESTED = 'DELETE_EVENT_REQUESTED';
export const DELETE_EVENT_STARTED = 'DELETE_EVENT_STARTED';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

export const LOAD_EVENT_DETAIL_REQUESTED = 'LOAD_EVENT_DETAIL_REQUESTED';
export const LOAD_EVENT_DETAIL_STARTED = 'LOAD_EVENT_DETAIL_STARTED';
export const LOAD_EVENT_DETAIL_SUCCESS = 'LOAD_EVENT_DETAIL_SUCCESS';
export const LOAD_EVENT_DETAIL_ERROR = 'LOAD_EVENT_DETAIL_ERROR';

export const JOIN_EVENT_REQUESTED = 'JOIN_EVENT_REQUESTED';
export const JOIN_EVENT_STARTED = 'JOIN_EVENT_STARTED';
export const JOIN_EVENT_SUCCESS = 'JOIN_EVENT_SUCCESS';
export const JOIN_EVENT_ERROR = 'JOIN_EVENT_ERROR';

export const LOAD_JOINED_EVENTS_REQUESTED = 'LOAD_JOINED_EVENTS_REQUESTED';
export const LOAD_JOINED_EVENTS_STARTED = 'LOAD_JOINED_EVENTS_STARTED';
export const LOAD_JOINED_EVENTS_SUCCESS = 'LOAD_JOINED_EVENTS_SUCCESS';
export const LOAD_JOINED_EVENTS_ERROR = 'LOAD_JOINED_EVENTS_ERROR';

export const LOAD_CREATED_EVENTS_REQUESTED = 'LOAD_CREATED_EVENTS_REQUESTED';
export const LOAD_CREATED_EVENTS_STARTED = 'LOAD_CREATED_EVENTS_STARTED';
export const LOAD_CREATED_EVENTS_SUCCESS = 'LOAD_CREATED_EVENTS_SUCCESS';
export const LOAD_CREATED_EVENTS_ERROR = 'LOAD_CREATED_EVENTS_ERROR';

export const LOAD_USER_EVENTS_REQUESTED = 'LOAD_USER_EVENTS_REQUESTED';
export const LOAD_USER_EVENTS_STARTED = 'LOAD_USER_EVENTS_STARTED';
export const LOAD_USER_EVENTS_SUCCESS = 'LOAD_USER_EVENTS_SUCCESS';
export const LOAD_USER_EVENTS_ERROR = 'LOAD_USER_EVENTS_ERROR';
