export const CREATE_MEMBERSHIP_REQUESTED = 'CREATE_MEMBERSHIP_REQUESTED';
export const CREATE_MEMBERSHIP_STARTED = 'CREATE_MEMBERSHIP_STARTED';
export const CREATE_MEMBERSHIP_SUCCESS = 'CREATE_MEMBERSHIP_SUCCESS';
export const CREATE_MEMBERSHIP_ERROR = 'CREATE_MEMBERSHIP_ERROR';

export const UPDATE_MEMBERSHIP_REQUESTED = 'UPDATE_MEMBERSHIP_REQUESTED';
export const UPDATE_MEMBERSHIP_STARTED = 'UPDATE_MEMBERSHIP_STARTED';
export const UPDATE_MEMBERSHIP_SUCCESS = 'UPDATE_MEMBERSHIP_SUCCESS';
export const UPDATE_MEMBERSHIP_ERROR = 'UPDATE_MEMBERSHIP_ERROR';

export const DELETE_MEMBERSHIP_REQUESTED = 'DELETE_MEMBERSHIP_REQUESTED';
export const DELETE_MEMBERSHIP_STARTED = 'DELETE_MEMBERSHIP_STARTED';
export const DELETE_MEMBERSHIP_SUCCESS = 'DELETE_MEMBERSHIP_SUCCESS';
export const DELETE_MEMBERSHIP_ERROR = 'DELETE_MEMBERSHIP_ERROR';

export const LOAD_MY_MEMBERSHIPS_REQUESTED = 'LOAD_MY_MEMBERSHIPS_REQUESTED';
export const LOAD_MY_MEMBERSHIPS_STARTED = 'LOAD_MY_MEMBERSHIPS_STARTED';
export const LOAD_MY_MEMBERSHIPS_SUCCESS = 'LOAD_MY_MEMBERSHIPS_SUCCESS';
export const LOAD_MY_MEMBERSHIPS_ERROR = 'LOAD_MY_MEMBERSHIPS_ERROR';
